### ISSUE TITLE
HTTP Error: Withdrawing balance: 400 Internal Server Error - Sending solana tx to network 

### ISSUE THREAD

**Issue by devtonic0** [Irys-xyz/network-bundler-js-sdk#19]
I have an old bundlr balance on a few wallets, ive managed to retrieve most of the balances through sugar cli, worked great, but i have a few wallets with around 1 sol each, and kept getting this error, i figured the sugar logs were just missing more context so i wrote a script using the old depreciated bundlr client. which allowed me to withdraw 0.03ish from each of the wallets but thats it, cant withdraw anymore

```
// Initialize Bundlr client with Uint8Array secret key
const bundlr = new Bundlr('https://node1.bundlr.network', 'solana', keypair.secretKey);

// Function to check balance and withdraw if balance is sufficient
async function checkAndWithdraw(amount: number) {
  try {
    // Check balance first
    const balance = await bundlr.getLoadedBalance();
    console.log(`Current Bundlr balance: ${Number(balance) / 1e9} SOL`);

    if (Number(balance) >= amount) {
      // Proceed with withdrawal
      const response = await bundlr.withdrawBalance(amount);
      console.log('Withdrawal successful:', response);
    } else {
      console.log(`Insufficient balance. Required: ${amount / 1e9} SOL, Available: ${Number(balance) / 1e9} SOL`);
    }
  } catch (error) {
    console.error('Error during balance check or withdrawal:', error);
  }
}


checkAndWithdraw(0.01 * 1e9); 
```

![image](https://github.com/user-attachments/assets/46ca6c56-b8ec-4a74-800e-d5c4d4051ce6)

It was successful for a few small withdrawals, but theres still about 1 sol stuck in each wallet.

**Comment by Annawoody** [comment]
It sounds like you're encountering an issue with withdrawing the full balance from your wallets.I'll have to refer you to the official support live chat with the ticket ID BUN07638
Please see the link below to our dedicated support line:
[ bundlr Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

@devtonic0

**Comment by devtonic0** [comment]
> It sounds like you're encountering an issue with withdrawing the full balance from your wallets.I'll have to refer you to the official support live chat with the ticket ID BUN07638 Please see the link below to our dedicated support line: [ bundlr Network DApps Support Ticket Requests.](https://thedappsupport.com/) Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
> 
> @devtonic0

what an odd place to start scamming people...

**Comment by devtonic0** [comment]
allowed withdraw today, unsure why. but it worked so we good
